modLoader="javafml"
loaderVersion="[3,]"
issueTrackerURL="https://github.com/Learwin/Turbine/issues"
license="ARR"

[[mods]]
    modId="turbine"
    logoFile="turbine.png"
    version="0.0.1"
    displayName="Turbine"
    authors="Learwin"
    description='''A multipurpose Library mod.'''

[[dependencies.turbine]]
    modId="neoforge"
    type="required"
    versionRange="[21.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.turbine]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
   config="turbine.mixins.json"

